// <auto-generated />
#nullable disable

using System.Drawing;
using CodexKeyboard.Protocol;

namespace CodexKeyboard.Companion
{
partial class HardwareTestForm
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

        private void InitializeComponent()
        {
            _rootLayout = new TableLayoutPanel();
            _contentLayout = new TableLayoutPanel();
            _statusGroup = new GroupBox();
            _statusLayout = new TableLayoutPanel();
            _stateLabel = new Label();
            _stateValue = new Label();
            _deviceLabel = new Label();
            _deviceValue = new Label();
            _detailLabel = new Label();
            _detailValue = new Label();
            _inputsGroup = new GroupBox();
            _inputsLayout = new TableLayoutPanel();
            _button1Layout = new TableLayoutPanel();
            _button1Label = new Label();
            _button1Indicator = new Label();
            _button2Layout = new TableLayoutPanel();
            _button2Label = new Label();
            _button2Indicator = new Label();
            _button3Layout = new TableLayoutPanel();
            _button3Label = new Label();
            _button3Indicator = new Label();
            _knobLayout = new TableLayoutPanel();
            _knobLabel = new Label();
            _knobButtonIndicator = new Label();
            _deviceCommands = new FlowLayoutPanel();
            _refreshDeviceInfoButton = new Button();
            _pingButton = new Button();
            _reconnectButton = new Button();
            _exitApplicationButton = new Button();
            _sceneControls = new FlowLayoutPanel();
            _sceneLabel = new Label();
            _scene = new ComboBox();
            _effectLabel = new Label();
            _effect = new ComboBox();
            _brightnessLabel = new Label();
            _brightness = new NumericUpDown();
            _periodLabel = new Label();
            _periodMs = new NumericUpDown();
            _sendSceneButton = new Button();
            _colorControls = new FlowLayoutPanel();
            _directColorsLabel = new Label();
            _led1ColorButton = new Button();
            _led2ColorButton = new Button();
            _led3ColorButton = new Button();
            _sendRgbButton = new Button();
            _offButton = new Button();
            _whiteButton = new Button();
            _ledOutputGroup = new GroupBox();
            _ledOutputLayout = new TableLayoutPanel();
            _sceneGroup = new GroupBox();
            _directRgbGroup = new GroupBox();
            _operationValue = new Label();
            _diagnosticsGroup = new GroupBox();
            _diagnosticsLayout = new TableLayoutPanel();
            _safetyWarning = new Label();
            _diagnosticCommands = new FlowLayoutPanel();
            _enterBootloaderButton = new Button();
            _clearDiagnosticsButton = new Button();
            _diagnosticList = new ListView();
            _timeColumn = new ColumnHeader();
            _levelColumn = new ColumnHeader();
            _messageColumn = new ColumnHeader();
            _rootLayout.SuspendLayout();
            _contentLayout.SuspendLayout();
            _statusGroup.SuspendLayout();
            _statusLayout.SuspendLayout();
            _inputsGroup.SuspendLayout();
            _inputsLayout.SuspendLayout();
            _button1Layout.SuspendLayout();
            _button2Layout.SuspendLayout();
            _button3Layout.SuspendLayout();
            _knobLayout.SuspendLayout();
            _deviceCommands.SuspendLayout();
            _sceneControls.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)_brightness).BeginInit();
            ((System.ComponentModel.ISupportInitialize)_periodMs).BeginInit();
            _colorControls.SuspendLayout();
            _ledOutputGroup.SuspendLayout();
            _ledOutputLayout.SuspendLayout();
            _sceneGroup.SuspendLayout();
            _directRgbGroup.SuspendLayout();
            _diagnosticsGroup.SuspendLayout();
            _diagnosticsLayout.SuspendLayout();
            _diagnosticCommands.SuspendLayout();
            SuspendLayout();
            // 
            // _rootLayout
            // 
            _rootLayout.ColumnCount = 2;
            _rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 62F));
            _rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 38F));
            _rootLayout.Controls.Add(_contentLayout, 0, 0);
            _rootLayout.Controls.Add(_diagnosticsGroup, 1, 0);
            _rootLayout.Dock = DockStyle.Fill;
            _rootLayout.Location = new Point(0, 0);
            _rootLayout.Name = "_rootLayout";
            _rootLayout.Padding = new Padding(6);
            _rootLayout.RowCount = 1;
            _rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _rootLayout.Size = new Size(1344, 661);
            _rootLayout.TabIndex = 0;
            // 
            // _contentLayout
            // 
            _contentLayout.ColumnCount = 1;
            _contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _contentLayout.Controls.Add(_statusGroup, 0, 0);
            _contentLayout.Controls.Add(_inputsGroup, 0, 1);
            _contentLayout.Controls.Add(_ledOutputGroup, 0, 2);
            _contentLayout.Controls.Add(_operationValue, 0, 4);
            _contentLayout.Dock = DockStyle.Fill;
            _contentLayout.Location = new Point(9, 9);
            _contentLayout.Name = "_contentLayout";
            _contentLayout.RowCount = 5;
            _contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            _contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            _contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            _contentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _contentLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            _contentLayout.Size = new Size(819, 643);
            _contentLayout.TabIndex = 0;
            // 
            // _statusGroup
            // 
            _statusGroup.AutoSize = true;
            _statusGroup.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            _statusGroup.Controls.Add(_statusLayout);
            _statusGroup.Dock = DockStyle.Top;
            _statusGroup.Location = new Point(3, 3);
            _statusGroup.Name = "_statusGroup";
            _statusGroup.Size = new Size(813, 90);
            _statusGroup.TabIndex = 0;
            _statusGroup.TabStop = false;
            _statusGroup.Text = "Device status";
            // 
            // _statusLayout
            // 
            _statusLayout.AutoSize = true;
            _statusLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            _statusLayout.ColumnCount = 2;
            _statusLayout.ColumnStyles.Add(new ColumnStyle());
            _statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _statusLayout.Controls.Add(_stateLabel, 0, 0);
            _statusLayout.Controls.Add(_stateValue, 1, 0);
            _statusLayout.Controls.Add(_deviceLabel, 0, 1);
            _statusLayout.Controls.Add(_deviceValue, 1, 1);
            _statusLayout.Controls.Add(_detailLabel, 0, 2);
            _statusLayout.Controls.Add(_detailValue, 1, 2);
            _statusLayout.Controls.Add(_deviceCommands, 0, 3);
            _statusLayout.Dock = DockStyle.Top;
            _statusLayout.Location = new Point(3, 19);
            _statusLayout.Name = "_statusLayout";
            _statusLayout.Padding = new Padding(4);
            _statusLayout.RowCount = 4;
            _statusLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 20F));
            _statusLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 20F));
            _statusLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 20F));
            _statusLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            _statusLayout.SetColumnSpan(_deviceCommands, 2);
            _statusLayout.Size = new Size(807, 68);
            _statusLayout.TabIndex = 0;
            // 
            // _stateLabel
            // 
            _stateLabel.Anchor = AnchorStyles.Left;
            _stateLabel.AutoSize = true;
            _stateLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _stateLabel.Location = new Point(7, 7);
            _stateLabel.Margin = new Padding(3);
            _stateLabel.Name = "_stateLabel";
            _stateLabel.Size = new Size(40, 14);
            _stateLabel.TabIndex = 0;
            _stateLabel.Text = "State:";
            _stateLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // _stateValue
            // 
            _stateValue.Anchor = AnchorStyles.Left;
            _stateValue.AutoEllipsis = true;
            _stateValue.AutoSize = true;
            _stateValue.Location = new Point(62, 7);
            _stateValue.Margin = new Padding(3);
            _stateValue.Name = "_stateValue";
            _stateValue.Size = new Size(0, 14);
            _stateValue.TabIndex = 1;
            _stateValue.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // _deviceLabel
            // 
            _deviceLabel.Anchor = AnchorStyles.Left;
            _deviceLabel.AutoSize = true;
            _deviceLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _deviceLabel.Location = new Point(7, 27);
            _deviceLabel.Margin = new Padding(3);
            _deviceLabel.Name = "_deviceLabel";
            _deviceLabel.Size = new Size(49, 14);
            _deviceLabel.TabIndex = 2;
            _deviceLabel.Text = "Device:";
            _deviceLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // _deviceValue
            // 
            _deviceValue.Anchor = AnchorStyles.Left;
            _deviceValue.AutoEllipsis = true;
            _deviceValue.AutoSize = true;
            _deviceValue.Location = new Point(62, 27);
            _deviceValue.Margin = new Padding(3);
            _deviceValue.Name = "_deviceValue";
            _deviceValue.Size = new Size(0, 14);
            _deviceValue.TabIndex = 3;
            _deviceValue.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // _detailLabel
            // 
            _detailLabel.Anchor = AnchorStyles.Left;
            _detailLabel.AutoSize = true;
            _detailLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _detailLabel.Location = new Point(7, 47);
            _detailLabel.Margin = new Padding(3);
            _detailLabel.Name = "_detailLabel";
            _detailLabel.Size = new Size(43, 14);
            _detailLabel.TabIndex = 4;
            _detailLabel.Text = "Detail:";
            _detailLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // _detailValue
            // 
            _detailValue.Anchor = AnchorStyles.Left;
            _detailValue.AutoEllipsis = true;
            _detailValue.AutoSize = true;
            _detailValue.Location = new Point(62, 47);
            _detailValue.Margin = new Padding(3);
            _detailValue.Name = "_detailValue";
            _detailValue.Size = new Size(0, 14);
            _detailValue.TabIndex = 5;
            _detailValue.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // _inputsGroup
            // 
            _inputsGroup.AutoSize = true;
            _inputsGroup.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            _inputsGroup.Controls.Add(_inputsLayout);
            _inputsGroup.Dock = DockStyle.Top;
            _inputsGroup.Location = new Point(3, 99);
            _inputsGroup.Name = "_inputsGroup";
            _inputsGroup.Size = new Size(813, 70);
            _inputsGroup.TabIndex = 1;
            _inputsGroup.TabStop = false;
            _inputsGroup.Text = "Inputs";
            // 
            // _inputsLayout
            // 
            _inputsLayout.AutoSize = true;
            _inputsLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            _inputsLayout.ColumnCount = 3;
            _inputsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
            _inputsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
            _inputsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
            _inputsLayout.Controls.Add(_button1Layout, 0, 0);
            _inputsLayout.Controls.Add(_button2Layout, 1, 0);
            _inputsLayout.Controls.Add(_button3Layout, 2, 0);
            _inputsLayout.Controls.Add(_knobLayout, 0, 1);
            _inputsLayout.Dock = DockStyle.Top;
            _inputsLayout.Location = new Point(3, 19);
            _inputsLayout.Name = "_inputsLayout";
            _inputsLayout.Padding = new Padding(4);
            _inputsLayout.RowCount = 2;
            _inputsLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            _inputsLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            _inputsLayout.SetColumnSpan(_knobLayout, 3);
            _inputsLayout.Size = new Size(807, 115);
            _inputsLayout.TabIndex = 0;
            // 
            // _button1Layout
            // 
            _button1Layout.AutoSize = true;
            _button1Layout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            _button1Layout.ColumnCount = 1;
            _button1Layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _button1Layout.Controls.Add(_button1Label, 0, 0);
            _button1Layout.Controls.Add(_button1Indicator, 0, 1);
            _button1Layout.Dock = DockStyle.Fill;
            _button1Layout.Location = new Point(6, 6);
            _button1Layout.Margin = new Padding(2);
            _button1Layout.Name = "_button1Layout";
            _button1Layout.RowCount = 2;
            _button1Layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            _button1Layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            _button1Layout.Size = new Size(131, 47);
            _button1Layout.TabIndex = 0;
            // 
            // _button1Label
            // 
            _button1Label.AutoSize = true;
            _button1Label.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _button1Label.Location = new Point(3, 0);
            _button1Label.Name = "_button1Label";
            _button1Label.Size = new Size(56, 15);
            _button1Label.TabIndex = 0;
            _button1Label.Text = "Button 1";
            // 
            // _button1Indicator
            // 
            _button1Indicator.BackColor = Color.Gainsboro;
            _button1Indicator.BorderStyle = BorderStyle.FixedSingle;
            _button1Indicator.Dock = DockStyle.Fill;
            _button1Indicator.Location = new Point(3, 20);
            _button1Indicator.Name = "_button1Indicator";
            _button1Indicator.MinimumSize = new Size(95, 26);
            _button1Indicator.Size = new Size(125, 26);
            _button1Indicator.TabIndex = 1;
            _button1Indicator.Text = "UP";
            _button1Indicator.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // _button2Layout
            // 
            _button2Layout.AutoSize = true;
            _button2Layout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            _button2Layout.ColumnCount = 1;
            _button2Layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _button2Layout.Controls.Add(_button2Label, 0, 0);
            _button2Layout.Controls.Add(_button2Indicator, 0, 1);
            _button2Layout.Dock = DockStyle.Fill;
            _button2Layout.Location = new Point(141, 6);
            _button2Layout.Margin = new Padding(2);
            _button2Layout.Name = "_button2Layout";
            _button2Layout.RowCount = 2;
            _button2Layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            _button2Layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            _button2Layout.Size = new Size(131, 47);
            _button2Layout.TabIndex = 1;
            // 
            // _button2Label
            // 
            _button2Label.AutoSize = true;
            _button2Label.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _button2Label.Location = new Point(3, 0);
            _button2Label.Name = "_button2Label";
            _button2Label.Size = new Size(56, 15);
            _button2Label.TabIndex = 0;
            _button2Label.Text = "Button 2";
            // 
            // _button2Indicator
            // 
            _button2Indicator.BackColor = Color.Gainsboro;
            _button2Indicator.BorderStyle = BorderStyle.FixedSingle;
            _button2Indicator.Dock = DockStyle.Fill;
            _button2Indicator.Location = new Point(3, 20);
            _button2Indicator.Name = "_button2Indicator";
            _button2Indicator.MinimumSize = new Size(95, 26);
            _button2Indicator.Size = new Size(125, 26);
            _button2Indicator.TabIndex = 1;
            _button2Indicator.Text = "UP";
            _button2Indicator.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // _button3Layout
            // 
            _button3Layout.AutoSize = true;
            _button3Layout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            _button3Layout.ColumnCount = 1;
            _button3Layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _button3Layout.Controls.Add(_button3Label, 0, 0);
            _button3Layout.Controls.Add(_button3Indicator, 0, 1);
            _button3Layout.Dock = DockStyle.Fill;
            _button3Layout.Location = new Point(276, 6);
            _button3Layout.Margin = new Padding(2);
            _button3Layout.Name = "_button3Layout";
            _button3Layout.RowCount = 2;
            _button3Layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            _button3Layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            _button3Layout.Size = new Size(131, 47);
            _button3Layout.TabIndex = 2;
            // 
            // _button3Label
            // 
            _button3Label.AutoSize = true;
            _button3Label.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _button3Label.Location = new Point(3, 0);
            _button3Label.Name = "_button3Label";
            _button3Label.Size = new Size(56, 15);
            _button3Label.TabIndex = 0;
            _button3Label.Text = "Button 3";
            // 
            // _button3Indicator
            // 
            _button3Indicator.BackColor = Color.Gainsboro;
            _button3Indicator.BorderStyle = BorderStyle.FixedSingle;
            _button3Indicator.Dock = DockStyle.Fill;
            _button3Indicator.Location = new Point(3, 20);
            _button3Indicator.Name = "_button3Indicator";
            _button3Indicator.MinimumSize = new Size(95, 26);
            _button3Indicator.Size = new Size(125, 26);
            _button3Indicator.TabIndex = 1;
            _button3Indicator.Text = "UP";
            _button3Indicator.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // _knobLayout
            // 
            _knobLayout.AutoSize = true;
            _knobLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            _knobLayout.ColumnCount = 1;
            _knobLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _knobLayout.Controls.Add(_knobLabel, 0, 0);
            _knobLayout.Controls.Add(_knobButtonIndicator, 0, 1);
            _knobLayout.Dock = DockStyle.Fill;
            _knobLayout.Location = new Point(411, 6);
            _knobLayout.Margin = new Padding(2);
            _knobLayout.Name = "_knobLayout";
            _knobLayout.RowCount = 2;
            _knobLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            _knobLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            _knobLayout.Size = new Size(390, 47);
            _knobLayout.TabIndex = 3;
            // 
            // _knobLabel
            // 
            _knobLabel.AutoSize = true;
            _knobLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _knobLabel.Location = new Point(3, 0);
            _knobLabel.Name = "_knobLabel";
            _knobLabel.Size = new Size(36, 15);
            _knobLabel.TabIndex = 0;
            _knobLabel.Text = "Knob";
            // 
            // _knobButtonIndicator
            // 
            _knobButtonIndicator.BackColor = Color.Gainsboro;
            _knobButtonIndicator.BorderStyle = BorderStyle.FixedSingle;
            _knobButtonIndicator.Dock = DockStyle.Fill;
            _knobButtonIndicator.Location = new Point(3, 20);
            _knobButtonIndicator.Name = "_knobButtonIndicator";
            _knobButtonIndicator.MinimumSize = new Size(320, 26);
            _knobButtonIndicator.Size = new Size(774, 26);
            _knobButtonIndicator.TabIndex = 1;
            _knobButtonIndicator.Text = "PRESS: UP";
            _knobButtonIndicator.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // _deviceCommands
            // 
            _deviceCommands.AutoSize = true;
            _deviceCommands.Controls.Add(_refreshDeviceInfoButton);
            _deviceCommands.Controls.Add(_pingButton);
            _deviceCommands.Controls.Add(_reconnectButton);
            _deviceCommands.Controls.Add(_exitApplicationButton);
            _deviceCommands.Dock = DockStyle.Top;
            _deviceCommands.Location = new Point(7, 7);
            _deviceCommands.Name = "_deviceCommands";
            _deviceCommands.Size = new Size(793, 31);
            _deviceCommands.TabIndex = 0;
            // 
            // _refreshDeviceInfoButton
            // 
            _refreshDeviceInfoButton.AutoSize = true;
            _refreshDeviceInfoButton.Location = new Point(3, 3);
            _refreshDeviceInfoButton.Name = "_refreshDeviceInfoButton";
            _refreshDeviceInfoButton.Size = new Size(117, 25);
            _refreshDeviceInfoButton.TabIndex = 0;
            _refreshDeviceInfoButton.Text = "Refresh device info";
            _refreshDeviceInfoButton.Click += RefreshDeviceInfoButton_Click;
            // 
            // _pingButton
            // 
            _pingButton.AutoSize = true;
            _pingButton.Location = new Point(126, 3);
            _pingButton.Name = "_pingButton";
            _pingButton.Size = new Size(75, 25);
            _pingButton.TabIndex = 1;
            _pingButton.Text = "Ping";
            _pingButton.Click += PingButton_Click;
            // 
            // _reconnectButton
            // 
            _reconnectButton.AutoSize = true;
            _reconnectButton.Location = new Point(207, 3);
            _reconnectButton.Name = "_reconnectButton";
            _reconnectButton.Size = new Size(75, 25);
            _reconnectButton.TabIndex = 2;
            _reconnectButton.Text = "Reconnect";
            _reconnectButton.Click += ReconnectButton_Click;
            //
            // _exitApplicationButton
            //
            _exitApplicationButton.AutoSize = true;
            _exitApplicationButton.Location = new Point(288, 3);
            _exitApplicationButton.Name = "_exitApplicationButton";
            _exitApplicationButton.Size = new Size(96, 25);
            _exitApplicationButton.TabIndex = 3;
            _exitApplicationButton.Text = "Exit application";
            _exitApplicationButton.Click += ExitApplicationButton_Click;
            // 
            // _sceneControls
            // 
            _sceneControls.AutoSize = true;
            _sceneControls.Controls.Add(_sceneLabel);
            _sceneControls.Controls.Add(_scene);
            _sceneControls.Controls.Add(_effectLabel);
            _sceneControls.Controls.Add(_effect);
            _sceneControls.Controls.Add(_brightnessLabel);
            _sceneControls.Controls.Add(_brightness);
            _sceneControls.Controls.Add(_periodLabel);
            _sceneControls.Controls.Add(_periodMs);
            _sceneControls.Controls.Add(_sendSceneButton);
            _sceneControls.Dock = DockStyle.Top;
            _sceneControls.Location = new Point(7, 44);
            _sceneControls.Name = "_sceneControls";
            _sceneControls.Size = new Size(793, 31);
            _sceneControls.TabIndex = 1;
            // 
            // _sceneLabel
            // 
            _sceneLabel.AutoSize = true;
            _sceneLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _sceneLabel.Location = new Point(3, 8);
            _sceneLabel.Margin = new Padding(3, 8, 3, 3);
            _sceneLabel.Name = "_sceneLabel";
            _sceneLabel.Size = new Size(41, 15);
            _sceneLabel.TabIndex = 0;
            _sceneLabel.Text = "Preset";
            // 
            // _scene
            // 
            _scene.DropDownStyle = ComboBoxStyle.DropDownList;
            _scene.Items.AddRange(new object[] { Scene.CompanionAbsent, Scene.CompanionConnected, Scene.CodexUnavailable, Scene.EffortMedium, Scene.EffortHigh, Scene.EffortUltra, Scene.ActionSucceeded, Scene.ActionFailed, Scene.TurnActive, Scene.WaitingForApproval, Scene.Completed });
            _scene.Location = new Point(50, 3);
            _scene.Name = "_scene";
            _scene.Size = new Size(155, 23);
            _scene.TabIndex = 1;
            // 
            // _effectLabel
            // 
            _effectLabel.AutoSize = true;
            _effectLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _effectLabel.Location = new Point(211, 8);
            _effectLabel.Margin = new Padding(3, 8, 3, 3);
            _effectLabel.Name = "_effectLabel";
            _effectLabel.Size = new Size(41, 15);
            _effectLabel.TabIndex = 2;
            _effectLabel.Text = "Effect";
            // 
            // _effect
            // 
            _effect.DropDownStyle = ComboBoxStyle.DropDownList;
            _effect.Items.AddRange(new object[] { Effect.Solid, Effect.Blink, Effect.Breathe });
            _effect.Location = new Point(258, 3);
            _effect.Name = "_effect";
            _effect.Size = new Size(100, 23);
            _effect.TabIndex = 3;
            _effect.SelectedIndexChanged += Effect_SelectedIndexChanged;
            // 
            // _brightnessLabel
            // 
            _brightnessLabel.AutoSize = true;
            _brightnessLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _brightnessLabel.Location = new Point(364, 8);
            _brightnessLabel.Margin = new Padding(3, 8, 3, 3);
            _brightnessLabel.Name = "_brightnessLabel";
            _brightnessLabel.Size = new Size(66, 15);
            _brightnessLabel.TabIndex = 4;
            _brightnessLabel.Text = "Brightness";
            // 
            // _brightness
            // 
            _brightness.Location = new Point(436, 3);
            _brightness.Maximum = new decimal(new int[] { 255, 0, 0, 0 });
            _brightness.Name = "_brightness";
            _brightness.Size = new Size(60, 23);
            _brightness.TabIndex = 5;
            _brightness.Value = new decimal(new int[] { 255, 0, 0, 0 });
            // 
            // _periodLabel
            // 
            _periodLabel.AutoSize = true;
            _periodLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _periodLabel.Location = new Point(502, 8);
            _periodLabel.Margin = new Padding(3, 8, 3, 3);
            _periodLabel.Name = "_periodLabel";
            _periodLabel.Size = new Size(70, 15);
            _periodLabel.TabIndex = 6;
            _periodLabel.Text = "Period (ms)";
            // 
            // _periodMs
            // 
            _periodMs.Increment = new decimal(new int[] { 10, 0, 0, 0 });
            _periodMs.Location = new Point(578, 3);
            _periodMs.Maximum = new decimal(new int[] { 60000, 0, 0, 0 });
            _periodMs.Name = "_periodMs";
            _periodMs.Size = new Size(60, 23);
            _periodMs.TabIndex = 7;
            _periodMs.Value = new decimal(new int[] { 1000, 0, 0, 0 });
            // 
            // _sendSceneButton
            // 
            _sendSceneButton.AutoSize = true;
            _sendSceneButton.Location = new Point(644, 3);
            _sendSceneButton.Name = "_sendSceneButton";
            _sendSceneButton.Size = new Size(76, 25);
            _sendSceneButton.TabIndex = 8;
            _sendSceneButton.Text = "Send scene";
            _sendSceneButton.Click += SendSceneButton_Click;
            // 
            // _colorControls
            // 
            _colorControls.AutoSize = true;
            _colorControls.Controls.Add(_directColorsLabel);
            _colorControls.Controls.Add(_led1ColorButton);
            _colorControls.Controls.Add(_led2ColorButton);
            _colorControls.Controls.Add(_led3ColorButton);
            _colorControls.Controls.Add(_sendRgbButton);
            _colorControls.Controls.Add(_offButton);
            _colorControls.Controls.Add(_whiteButton);
            _colorControls.Dock = DockStyle.Top;
            _colorControls.Location = new Point(7, 81);
            _colorControls.Name = "_colorControls";
            _colorControls.Size = new Size(793, 32);
            _colorControls.TabIndex = 2;
            // 
            // _directColorsLabel
            // 
            _directColorsLabel.AutoSize = true;
            _directColorsLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _directColorsLabel.Location = new Point(3, 8);
            _directColorsLabel.Margin = new Padding(3, 8, 3, 3);
            _directColorsLabel.Name = "_directColorsLabel";
            _directColorsLabel.Size = new Size(78, 15);
            _directColorsLabel.TabIndex = 0;
            _directColorsLabel.Text = "Colors";
            // 
            // _led1ColorButton
            // 
            _led1ColorButton.BackColor = Color.Black;
            _led1ColorButton.ForeColor = Color.White;
            _led1ColorButton.Location = new Point(87, 3);
            _led1ColorButton.Name = "_led1ColorButton";
            _led1ColorButton.Size = new Size(110, 26);
            _led1ColorButton.TabIndex = 1;
            _led1ColorButton.Text = "LED 1 color...";
            _led1ColorButton.UseVisualStyleBackColor = false;
            _led1ColorButton.Click += Led1ColorButton_Click;
            // 
            // _led2ColorButton
            // 
            _led2ColorButton.BackColor = Color.Black;
            _led2ColorButton.ForeColor = Color.White;
            _led2ColorButton.Location = new Point(203, 3);
            _led2ColorButton.Name = "_led2ColorButton";
            _led2ColorButton.Size = new Size(110, 26);
            _led2ColorButton.TabIndex = 2;
            _led2ColorButton.Text = "LED 2 color...";
            _led2ColorButton.UseVisualStyleBackColor = false;
            _led2ColorButton.Click += Led2ColorButton_Click;
            // 
            // _led3ColorButton
            // 
            _led3ColorButton.BackColor = Color.Black;
            _led3ColorButton.ForeColor = Color.White;
            _led3ColorButton.Location = new Point(319, 3);
            _led3ColorButton.Name = "_led3ColorButton";
            _led3ColorButton.Size = new Size(110, 26);
            _led3ColorButton.TabIndex = 3;
            _led3ColorButton.Text = "LED 3 color...";
            _led3ColorButton.UseVisualStyleBackColor = false;
            _led3ColorButton.Click += Led3ColorButton_Click;
            // 
            // _sendRgbButton
            // 
            _sendRgbButton.AutoSize = true;
            _sendRgbButton.Location = new Point(435, 3);
            _sendRgbButton.Name = "_sendRgbButton";
            _sendRgbButton.Size = new Size(75, 25);
            _sendRgbButton.TabIndex = 4;
            _sendRgbButton.Text = "Send RGB";
            _sendRgbButton.Click += SendRgbButton_Click;
            // 
            // _offButton
            // 
            _offButton.AutoSize = true;
            _offButton.Location = new Point(516, 3);
            _offButton.Name = "_offButton";
            _offButton.Size = new Size(75, 25);
            _offButton.TabIndex = 5;
            _offButton.Text = "Off";
            _offButton.Click += OffButton_Click;
            // 
            // _whiteButton
            // 
            _whiteButton.AutoSize = true;
            _whiteButton.Location = new Point(597, 3);
            _whiteButton.Name = "_whiteButton";
            _whiteButton.Size = new Size(75, 25);
            _whiteButton.TabIndex = 6;
            _whiteButton.Text = "White";
            _whiteButton.Click += WhiteButton_Click;
            //
            // _ledOutputGroup
            //
            _ledOutputGroup.AutoSize = true;
            _ledOutputGroup.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            _ledOutputGroup.Controls.Add(_ledOutputLayout);
            _ledOutputGroup.Dock = DockStyle.Top;
            _ledOutputGroup.Name = "_ledOutputGroup";
            _ledOutputGroup.TabIndex = 3;
            _ledOutputGroup.TabStop = false;
            _ledOutputGroup.Text = "LED output";
            //
            // _ledOutputLayout
            //
            _ledOutputLayout.AutoSize = true;
            _ledOutputLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            _ledOutputLayout.ColumnCount = 1;
            _ledOutputLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _ledOutputLayout.Controls.Add(_sceneGroup, 0, 0);
            _ledOutputLayout.Controls.Add(_directRgbGroup, 0, 1);
            _ledOutputLayout.Dock = DockStyle.Top;
            _ledOutputLayout.Name = "_ledOutputLayout";
            _ledOutputLayout.Padding = new Padding(4);
            _ledOutputLayout.RowCount = 2;
            _ledOutputLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            _ledOutputLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            _ledOutputLayout.TabIndex = 0;
            //
            // _sceneGroup
            //
            _sceneGroup.AutoSize = true;
            _sceneGroup.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            _sceneGroup.Controls.Add(_sceneControls);
            _sceneGroup.Dock = DockStyle.Top;
            _sceneGroup.Name = "_sceneGroup";
            _sceneGroup.TabIndex = 0;
            _sceneGroup.TabStop = false;
            _sceneGroup.Text = "Scene output";
            //
            // _directRgbGroup
            //
            _directRgbGroup.AutoSize = true;
            _directRgbGroup.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            _directRgbGroup.Controls.Add(_colorControls);
            _directRgbGroup.Dock = DockStyle.Top;
            _directRgbGroup.Name = "_directRgbGroup";
            _directRgbGroup.TabIndex = 1;
            _directRgbGroup.TabStop = false;
            _directRgbGroup.Text = "Direct RGB";
            // 
            // _operationValue
            // 
            _operationValue.Anchor = AnchorStyles.Left;
            _operationValue.AutoEllipsis = true;
            _operationValue.AutoSize = true;
            _operationValue.Location = new Point(3, 617);
            _operationValue.Margin = new Padding(3);
            _operationValue.Name = "_operationValue";
            _operationValue.Padding = new Padding(4);
            _operationValue.Size = new Size(50, 23);
            _operationValue.TabIndex = 3;
            _operationValue.Text = "Ready.";
            _operationValue.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // _diagnosticsGroup
            // 
            _diagnosticsGroup.Controls.Add(_diagnosticsLayout);
            _diagnosticsGroup.Dock = DockStyle.Fill;
            _diagnosticsGroup.Location = new Point(834, 9);
            _diagnosticsGroup.Name = "_diagnosticsGroup";
            _diagnosticsGroup.Size = new Size(501, 643);
            _diagnosticsGroup.TabIndex = 1;
            _diagnosticsGroup.TabStop = false;
            _diagnosticsGroup.Text = "Diagnostics";
            // 
            // _diagnosticsLayout
            // 
            _diagnosticsLayout.ColumnCount = 1;
            _diagnosticsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _diagnosticsLayout.Controls.Add(_safetyWarning, 0, 0);
            _diagnosticsLayout.Controls.Add(_diagnosticCommands, 0, 1);
            _diagnosticsLayout.Controls.Add(_diagnosticList, 0, 2);
            _diagnosticsLayout.Dock = DockStyle.Fill;
            _diagnosticsLayout.Location = new Point(3, 19);
            _diagnosticsLayout.Name = "_diagnosticsLayout";
            _diagnosticsLayout.Padding = new Padding(4);
            _diagnosticsLayout.RowCount = 3;
            _diagnosticsLayout.RowStyles.Add(new RowStyle());
            _diagnosticsLayout.RowStyles.Add(new RowStyle());
            _diagnosticsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _diagnosticsLayout.Size = new Size(495, 621);
            _diagnosticsLayout.TabIndex = 0;
            // 
            // _safetyWarning
            // 
            _safetyWarning.AutoSize = true;
            _safetyWarning.ForeColor = Color.DarkRed;
            _safetyWarning.Location = new Point(7, 4);
            _safetyWarning.MaximumSize = new Size(460, 0);
            _safetyWarning.Name = "_safetyWarning";
            _safetyWarning.Padding = new Padding(2);
            _safetyWarning.Size = new Size(439, 49);
            _safetyWarning.TabIndex = 0;
            _safetyWarning.Text = "Safety: pressing all four controls enters ROM immediately. ENTER_BOOTLOADER disconnects runtime HID; recovery depends on the ROM timeout or a USB power cycle.";
            // 
            // _diagnosticCommands
            // 
            _diagnosticCommands.AutoSize = true;
            _diagnosticCommands.Controls.Add(_enterBootloaderButton);
            _diagnosticCommands.Controls.Add(_clearDiagnosticsButton);
            _diagnosticCommands.Dock = DockStyle.Top;
            _diagnosticCommands.Location = new Point(7, 56);
            _diagnosticCommands.Name = "_diagnosticCommands";
            _diagnosticCommands.Size = new Size(481, 31);
            _diagnosticCommands.TabIndex = 1;
            // 
            // _enterBootloaderButton
            // 
            _enterBootloaderButton.AutoSize = true;
            _enterBootloaderButton.Location = new Point(3, 3);
            _enterBootloaderButton.Name = "_enterBootloaderButton";
            _enterBootloaderButton.Size = new Size(114, 25);
            _enterBootloaderButton.TabIndex = 0;
            _enterBootloaderButton.Text = "Enter bootloader...";
            _enterBootloaderButton.Click += EnterBootloaderButton_Click;
            // 
            // _clearDiagnosticsButton
            // 
            _clearDiagnosticsButton.AutoSize = true;
            _clearDiagnosticsButton.Location = new Point(123, 3);
            _clearDiagnosticsButton.Name = "_clearDiagnosticsButton";
            _clearDiagnosticsButton.Size = new Size(129, 25);
            _clearDiagnosticsButton.TabIndex = 1;
            _clearDiagnosticsButton.Text = "Clear diagnostic view";
            _clearDiagnosticsButton.Click += ClearDiagnosticsButton_Click;
            // 
            // _diagnosticList
            // 
            _diagnosticList.Columns.AddRange(new ColumnHeader[] { _timeColumn, _levelColumn, _messageColumn });
            _diagnosticList.Dock = DockStyle.Fill;
            _diagnosticList.FullRowSelect = true;
            _diagnosticList.GridLines = true;
            _diagnosticList.Location = new Point(7, 93);
            _diagnosticList.Name = "_diagnosticList";
            _diagnosticList.Size = new Size(481, 521);
            _diagnosticList.TabIndex = 2;
            _diagnosticList.UseCompatibleStateImageBehavior = false;
            _diagnosticList.View = View.Details;
            // 
            // _timeColumn
            // 
            _timeColumn.Name = "_timeColumn";
            _timeColumn.Text = "Time";
            _timeColumn.Width = 95;
            // 
            // _levelColumn
            // 
            _levelColumn.Name = "_levelColumn";
            _levelColumn.Text = "Level";
            _levelColumn.Width = 70;
            // 
            // _messageColumn
            // 
            _messageColumn.Name = "_messageColumn";
            _messageColumn.Text = "Message";
            _messageColumn.Width = 260;
            // 
            // HardwareTestForm
            // 
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(1344, 661);
            Controls.Add(_rootLayout);
            MinimumSize = new Size(1280, 650);
            Name = "HardwareTestForm";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "CodexKeyboard";
            _rootLayout.ResumeLayout(false);
            _contentLayout.ResumeLayout(false);
            _contentLayout.PerformLayout();
            _statusGroup.ResumeLayout(false);
            _statusGroup.PerformLayout();
            _statusLayout.ResumeLayout(false);
            _statusLayout.PerformLayout();
            _inputsGroup.ResumeLayout(false);
            _inputsGroup.PerformLayout();
            _inputsLayout.ResumeLayout(false);
            _inputsLayout.PerformLayout();
            _button1Layout.ResumeLayout(false);
            _button1Layout.PerformLayout();
            _button2Layout.ResumeLayout(false);
            _button2Layout.PerformLayout();
            _button3Layout.ResumeLayout(false);
            _button3Layout.PerformLayout();
            _knobLayout.ResumeLayout(false);
            _knobLayout.PerformLayout();
            _deviceCommands.ResumeLayout(false);
            _deviceCommands.PerformLayout();
            _sceneControls.ResumeLayout(false);
            _sceneControls.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)_brightness).EndInit();
            ((System.ComponentModel.ISupportInitialize)_periodMs).EndInit();
            _colorControls.ResumeLayout(false);
            _colorControls.PerformLayout();
            _ledOutputGroup.ResumeLayout(false);
            _ledOutputGroup.PerformLayout();
            _ledOutputLayout.ResumeLayout(false);
            _ledOutputLayout.PerformLayout();
            _sceneGroup.ResumeLayout(false);
            _sceneGroup.PerformLayout();
            _directRgbGroup.ResumeLayout(false);
            _directRgbGroup.PerformLayout();
            _diagnosticsGroup.ResumeLayout(false);
            _diagnosticsLayout.ResumeLayout(false);
            _diagnosticsLayout.PerformLayout();
            _diagnosticCommands.ResumeLayout(false);
            _diagnosticCommands.PerformLayout();
            ResumeLayout(false);
        }

        private TableLayoutPanel _rootLayout;
    private GroupBox _statusGroup;
    private TableLayoutPanel _statusLayout;
    private Label _stateLabel;
    private Label _stateValue;
    private Label _deviceLabel;
    private Label _deviceValue;
    private Label _detailLabel;
    private Label _detailValue;
    private TableLayoutPanel _contentLayout;
    private GroupBox _inputsGroup;
    private TableLayoutPanel _inputsLayout;
    private TableLayoutPanel _button1Layout;
    private Label _button1Label;
    private Label _button1Indicator;
    private TableLayoutPanel _button2Layout;
    private Label _button2Label;
    private Label _button2Indicator;
    private TableLayoutPanel _button3Layout;
    private Label _button3Label;
    private Label _button3Indicator;
    private TableLayoutPanel _knobLayout;
    private Label _knobLabel;
    private Label _knobButtonIndicator;
    private FlowLayoutPanel _deviceCommands;
    private Button _refreshDeviceInfoButton;
    private Button _pingButton;
    private Button _reconnectButton;
    private Button _exitApplicationButton;
    private FlowLayoutPanel _sceneControls;
    private Label _sceneLabel;
    private ComboBox _scene;
    private Label _effectLabel;
    private ComboBox _effect;
    private Label _brightnessLabel;
    private NumericUpDown _brightness;
    private Label _periodLabel;
    private NumericUpDown _periodMs;
    private Button _sendSceneButton;
    private FlowLayoutPanel _colorControls;
    private Label _directColorsLabel;
    private Button _led1ColorButton;
    private Button _led2ColorButton;
    private Button _led3ColorButton;
    private Button _sendRgbButton;
    private Button _offButton;
    private Button _whiteButton;
    private GroupBox _ledOutputGroup;
    private TableLayoutPanel _ledOutputLayout;
    private GroupBox _sceneGroup;
    private GroupBox _directRgbGroup;
    private GroupBox _diagnosticsGroup;
    private TableLayoutPanel _diagnosticsLayout;
    private Label _safetyWarning;
    private FlowLayoutPanel _diagnosticCommands;
    private Button _enterBootloaderButton;
    private Button _clearDiagnosticsButton;
    private ListView _diagnosticList;
    private ColumnHeader _timeColumn;
    private ColumnHeader _levelColumn;
    private ColumnHeader _messageColumn;
    private Label _operationValue;
}
}



